// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blog.sql

package db

import (
	"context"
)

const getBlog = `-- name: GetBlog :one
SELECT id, title, description, author FROM blog_metadata
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBlog(ctx context.Context, id int32) (BlogMetadatum, error) {
	row := q.db.QueryRow(ctx, getBlog, id)
	var i BlogMetadatum
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Author,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, description, author FROM blog_metadata
order BY title
`

func (q *Queries) ListBlogs(ctx context.Context) ([]BlogMetadatum, error) {
	rows, err := q.db.Query(ctx, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogMetadatum
	for rows.Next() {
		var i BlogMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
