// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blog.sql

package db

import (
	"context"
)

const getBlog = `-- name: GetBlog :one
SELECT id, title, slug, description, author, created_by, created_at, updated_by, updated_at FROM blog_post
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBlog(ctx context.Context, id int32) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlog, id)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Author,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, slug, description, author, created_by, created_at, updated_by, updated_at FROM blog_post
order BY title
`

func (q *Queries) ListBlogs(ctx context.Context) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Author,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
