// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogMetadatum struct {
	ID          int32
	Title       pgtype.Text
	Description pgtype.Text
	Author      pgtype.Text
}
